---

- name: Install Nessus Agent from repo
  package:
    name: "{{nessus_agent_package}}"
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  become: true
  when: "'.deb' not in nessus_agent_package"

- name: Install Nessus Agent from .deb package
  apt: deb={{nessus_agent_package}}
  become: true
  when: "'.deb' in nessus_agent_package"

- name: Check agent link status
  command: /opt/nessus_agent/sbin/nessuscli agent status
  become: true
  ignore_errors: yes
  register: nessus_link

- name: Configure Nessus Agent
  command: >
      /opt/nessus_agent/sbin/nessuscli agent link
      --key={{nessus_agent_key}}
      --host={{nessus_agent_host}}
      --port={{nessus_agent_port}}
      --groups="{{nessus_agent_group}}"
  become: true
  when: nessus_link is failed
  notify: restart nessusagent

- name: Ensure nessusagent is started
  service:
    name: nessusagent
    state: started
    enabled: yes
  become: true
